### ISSUE TITLE
It seem the test is hangup

### ISSUE THREAD

**Issue by xiaojiaqi** [smartystreets/go-disruptor#2]
[root@default benchmark-disruptor]#  go test -v -bench=".*"
testing: warning: no tests to run
PASS
BenchmarkSharedWriterReserveOneContendedWrite   100000000               29.1 ns/op             0 B/op          0 allocs/op
BenchmarkSharedWriterReserveManyContendedWrite

[root@default benchmark-disruptor]# go version  
go version go1.3.3 linux/amd64

**Comment by joliver** [comment]
I've been able to consistently reproduce the problem locally. I'm running `go version go1.4.2 darwin/amd64`. I'm currently walking through the code to identify exactly what's happening.
