### ISSUE TITLE
Is this repo active ?

### ISSUE THREAD

**Issue by agnivade** [smartystreets/go-disruptor#3]
Hi there,

Just wanted to check if there is still active development going on in this repo. The README says that this is an pre-alpha release and the alpha release was planned on June 2014. Its 2017 now.

**Comment by joliver** [comment]
I would LOVE for this project to be active. One thing we're fighting against is the Go memory model. It doesn't have a lot of the primitives in place for proper memory fencing. The only workaround is to use Go-flavored assembly specific to each CPU architecture. We haven't committed any time or resources to working around this problem. If a member of the community shows a strong interest and is capable of pushing the project forward, we're interested in continuing.

**Comment by agnivade** [comment]
Ok thanks. I don't have a strong need to use anything faster than channels right now. But who knows in the future :wink:
